# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: docker.pkg.github.com
          # Username used to log against the Docker registry
          username: ${{ github.actor }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Image
        run: docker pull docker.pkg.github.com/lauchacarro/poc-githubpackages-docker/counter-image:main
      - name: Run Image
        run: docker run -i --rm docker.pkg.github.com/lauchacarro/poc-githubpackages-docker/counter-image:main 3
